export const NOTIFICATION_TYPES = [
  "PROPERTY_APPROVED",
  "PROPERTY_REJECTED",
  "INQUIRY_RECEIVED",
  "LEAD_ASSIGNED",
  "LEAD_STATUS_UPDATED",
  "VISIT_SCHEDULED",
  "NEGOTIATION_UPDATED",
  "TRANSACTION_UPDATED",
] as const;
export type NotificationType = (typeof NOTIFICATION_TYPES)[number];

export const AUDIT_ACTIONS = [
  "LOGIN",
  "LOGOUT",
  "ROLE_CHANGED",
  "USER_DEACTIVATED",
  "PROPERTY_APPROVED",
  "PROPERTY_REJECTED",
  "PROPERTY_UPDATED",
  "LEAD_CREATED",
  "LEAD_ASSIGNED",
  "LEAD_REASSIGNED",
  "NEGOTIATION_UPDATED",
  "TRANSACTION_UPDATED",
  "COMMISSION_UPDATED",
  "ADMIN_CREATED",
  "PERMISSION_CHANGED",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
